version: '3'
services:

  sandbox:
    image: ypingcn/golang-playground:sandbox-1.23.4
    restart: always
    command: -mode=server -listen=0.0.0.0:80 -workers=1 -untrusted-container=ypingcn/golang-playground:actuator-1.23.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - playground
    # depends_on:
    #   - memcached

  web:
    image: ypingcn/golang-playground:web-1.23.4
    restart: always
    environment:
      - SANDBOX_BACKEND_URL=http://sandbox:/run
      - MEMCACHED_ADDR=memcached:11211
      - GONOPROXY=
      - GONOSUMDB=
      - GOPRIVATE=
      - GIT_HOST=
      - NETRC_MACHINE=
      - NETRC_LOGIN=
      - NETRC_TOKEN=
    ports:
      - 8061:8080
    depends_on:
      - sandbox
    networks:
      - playground

  memcached:
    image: memcached:1.6.15-alpine
    command: memcached -m 64
    networks:
      - playground
networks: 
  playground: